/**
 * Build nax-icon assets from Tabler Icons webfont subset:
 * 1) map Tabler codepoints from catalog + tabler-codepoints.json
 * 2) subset Tabler font to mapped glyphs
 * 3) emit base64 and rewrite @font-face in nax-icon.uvue
 *
 * Usage:
 *   pip/python with fontTools
 *   place full Tabler ttf at static/nax-icon.source.ttf (or keep previous subset)
 *   optionally refresh assets/icons/tabler-codepoints.json from Tabler CSS
 *   node scripts/build-icons.mjs
 *
 * Source: https://tabler.io/icons (MIT)
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const root = path.resolve(__dirname, '..')

const catalogPath = path.join(root, 'assets', 'icons', 'catalog.json')
const tablerCpPath = path.join(root, 'assets', 'icons', 'tabler-codepoints.json')
const staticDir = path.join(root, 'static')
const iconsDir = path.join(root, 'icons')
const glyphsPath = path.join(iconsDir, 'glyphs.uts')
const codepointsPath = path.join(iconsDir, 'codepoints.json')
const uvuePath = path.join(root, 'components', 'nax-icon', 'nax-icon.uvue')
const base64Path = path.join(staticDir, 'nax-icon.base64.txt')

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true })
}

function resolveSourceFont() {
  const candidates = [
    path.join(staticDir, 'nax-icon.source.ttf'),
    path.join(root, 'node_modules', '@tabler', 'icons-webfont', 'dist', 'fonts', 'tabler-icons.ttf'),
    path.join(process.cwd(), 'node_modules', '@tabler', 'icons-webfont', 'dist', 'fonts', 'tabler-icons.ttf'),
    path.join(staticDir, 'nax-icon.ttf')
  ]
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate
  }
  return null
}

function loadTablerCodepoints() {
  if (fs.existsSync(tablerCpPath)) {
    return JSON.parse(fs.readFileSync(tablerCpPath, 'utf8'))
  }
  // fallback: parse local CSS dump if present
  const cssCandidates = [
    path.join(root, '_tabler-icons.css'),
    path.join(root, 'node_modules', '@tabler', 'icons-webfont', 'dist', 'tabler-icons.css')
  ]
  let css = null
  for (const p of cssCandidates) {
    if (fs.existsSync(p)) {
      css = fs.readFileSync(p, 'utf8')
      break
    }
  }
  if (css == null) return null
  const map = {}
  const re = /\.ti-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)";/g
  let m
  while ((m = re.exec(css)) != null) {
    map[m[1]] = parseInt(m[2], 16)
  }
  return map
}

function toUtsGlyph(codepoint) {
  return `\\u${codepoint.toString(16).toLowerCase().padStart(4, '0')}`
}

function writeGlyphsUts(mapping) {
  const lines = []
  lines.push('/**')
  lines.push(' * Auto-generated by scripts/build-icons.mjs')
  lines.push(' * Source: Tabler Icons webfont (MIT) subset mapping for nax-ui')
  lines.push(' * Do not edit by hand. Re-run: node scripts/build-icons.mjs')
  lines.push(' */')
  lines.push('')
  lines.push('export function getNaxIconGlyph(name : string) : string {')
  for (const item of mapping) {
    lines.push(`\tif (name == '${item.name}') {`)
    lines.push(`\t\treturn '${toUtsGlyph(item.codepoint)}'`)
    lines.push('\t}')
  }
  lines.push("\treturn ''")
  lines.push('}')
  lines.push('')
  lines.push('export function listNaxIconNames() : string[] {')
  lines.push('\treturn [')
  for (const item of mapping) {
    lines.push(`\t\t'${item.name}',`)
  }
  lines.push('\t]')
  lines.push('}')
  lines.push('')
  fs.writeFileSync(glyphsPath, lines.join('\n'), 'utf8')
}

function writeSubsetPython(codepoints) {
  const pyPath = path.join(staticDir, '_subset_tmp.py')
  const unicodes = [0x20, ...Object.values(codepoints)]
  const code = `
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.subset import Subsetter, Options
import base64

root = Path(r'''${root.replace(/\\/g, '\\\\')}''')
src = root / 'static' / 'nax-icon.source.ttf'
if not src.exists():
    src = root / 'static' / 'nax-icon.ttf'
out_ttf = root / 'static' / 'nax-icon.ttf'
out_woff = root / 'static' / 'nax-icon.woff'
out_b64 = root / 'static' / 'nax-icon.base64.txt'
unicodes = ${JSON.stringify(unicodes)}

font = TTFont(str(src))
options = Options()
options.layout_features = ['*']
options.name_IDs = ['*']
options.name_languages = ['*']
options.notdef_outline = True
options.recommended_glyphs = True
options.recalc_bounds = True
options.recalc_timestamp = False
subsetter = Subsetter(options=options)
subsetter.populate(unicodes=unicodes)
subsetter.subset(font)
# normalize vertical metrics for consistent uvue/web/mp rendering
upm = font['head'].unitsPerEm
font['hhea'].ascent = upm
font['hhea'].descent = 0
font['hhea'].lineGap = 0
font['OS/2'].sTypoAscender = upm
font['OS/2'].sTypoDescender = 0
font['OS/2'].sTypoLineGap = 0
font['OS/2'].usWinAscent = upm
font['OS/2'].usWinDescent = 0
font['OS/2'].fsSelection |= 1 << 7
# center glyphs in em square
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
glyf = font['glyf']
hmtx = font['hmtx']
for gname in list(glyf.keys()):
    if gname == '.notdef':
        continue
    g = glyf[gname]
    if g.numberOfContours == 0 and not getattr(g, 'components', None):
        hmtx[gname] = (upm, 0)
        continue
    g.recalcBounds(glyf)
    xMin, yMin, xMax, yMax = g.xMin, g.yMin, g.xMax, g.yMax
    if xMax <= xMin or yMax <= yMin:
        hmtx[gname] = (upm, 0)
        continue
    dx = upm / 2 - (xMin + xMax) / 2
    dy = upm / 2 - (yMin + yMax) / 2
    pen = TTGlyphPen(glyf)
    tpen = TransformPen(pen, (1, 0, 0, 1, dx, dy))
    g.draw(tpen, glyf)
    new_g = pen.glyph()
    new_g.recalcBounds(glyf)
    glyf[gname] = new_g
    hmtx[gname] = (upm, int(round(new_g.xMin)))
font.flavor = None
font.save(str(out_ttf))
font.flavor = 'woff'
font.save(str(out_woff))
b64 = base64.b64encode(out_ttf.read_bytes()).decode('ascii')
out_b64.write_text(b64, encoding='ascii')
print('subset ttf', out_ttf.stat().st_size, 'b64', len(b64))
`
  fs.writeFileSync(pyPath, code, 'utf8')
  return pyPath
}

function injectBase64IntoUvue(b64) {
  if (!fs.existsSync(uvuePath)) {
    throw new Error(`Missing component: ${uvuePath}`)
  }
  let uvue = fs.readFileSync(uvuePath, 'utf8')
  const face = [
    '\t/*',
    '\t * base64 内联字体：兼容微信小程序（禁止本地字体路径）',
    '\t * uvue/Harmony: @font-face 仅支持 font-family + src',
    '\t * 图标源：Tabler Icons (MIT) 语义子集',
    '\t */',
    '\t@font-face {',
    '\t\tfont-family: nax-icon;',
    `\t\tsrc: url('data:font/truetype;charset=utf-8;base64,${b64}') format('truetype');`,
    '\t}'
  ].join('\n')

  const re = /\t@font-face\s*\{[\s\S]*?font-family:\s*nax-icon;[\s\S]*?\t\}/
  const reWithComment = /\t\/\*\s*\n\t \*[\s\S]*?\*\/\s*\n\t@font-face\s*\{[\s\S]*?font-family:\s*nax-icon;[\s\S]*?\t\}/
  if (reWithComment.test(uvue)) {
    uvue = uvue.replace(reWithComment, face)
  } else if (re.test(uvue)) {
    uvue = uvue.replace(re, face)
  } else {
    throw new Error('Cannot find @font-face block in nax-icon.uvue')
  }
  fs.writeFileSync(uvuePath, uvue, 'utf8')
}

function patchUvueDocs() {
  if (!fs.existsSync(uvuePath)) return
  let uvue = fs.readFileSync(uvuePath, 'utf8')
  // refresh JSDoc source note if present
  uvue = uvue.replace(
    /默认图标集来自 Lucide[^。\n]*/g,
    '默认图标集来自 Tabler Icons（MIT）语义子集'
  )
  uvue = uvue.replace(
    /Lucide\(ISC\)语义子集/g,
    'Tabler Icons（MIT）语义子集'
  )
  // garbled encodings from previous files may not match; also patch common English markers
  if (uvue.includes('Lucide')) {
    uvue = uvue.replace(/Lucide/g, 'Tabler Icons')
  }
  fs.writeFileSync(uvuePath, uvue, 'utf8')
}

function main() {
  if (!fs.existsSync(catalogPath)) {
    throw new Error(`Missing catalog: ${catalogPath}`)
  }
  const catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'))
  const tablerCodepoints = loadTablerCodepoints()
  if (tablerCodepoints == null && !fs.existsSync(codepointsPath)) {
    throw new Error('tabler-codepoints.json missing and no existing codepoints.json')
  }

  ensureDir(staticDir)
  ensureDir(iconsDir)

  let mapping = []
  let codepoints = {}

  if (tablerCodepoints != null) {
    const srcFont = resolveSourceFont()
    if (srcFont == null) throw new Error('Tabler source font not found (static/nax-icon.source.ttf)')
    // keep source full font for subset input
    const sourceTtf = path.join(staticDir, 'nax-icon.source.ttf')
    if (path.resolve(srcFont) !== path.resolve(sourceTtf)) {
      fs.copyFileSync(srcFont, sourceTtf)
    }

    const missing = []
    for (const item of catalog) {
      const name = String(item.name || '').trim()
      const tabler = String(item.tabler || item.lucide || '').trim()
      if (tablerCodepoints[tabler] == null) {
        missing.push(`${name} <= ${tabler}`)
        continue
      }
      const cp = Number(tablerCodepoints[tabler])
      codepoints[name] = cp
      mapping.push({ name, tabler, codepoint: cp })
    }
    if (missing.length) throw new Error(`Missing Tabler codepoints:\n- ${missing.join('\n- ')}`)
    fs.writeFileSync(codepointsPath, JSON.stringify(codepoints, null, 2) + '\n', 'utf8')
    fs.writeFileSync(path.join(iconsDir, 'mapping.json'), JSON.stringify(mapping, null, 2) + '\n', 'utf8')
    writeGlyphsUts(mapping)
  } else {
    codepoints = JSON.parse(fs.readFileSync(codepointsPath, 'utf8'))
    mapping = Object.keys(codepoints).map((name) => ({ name, codepoint: codepoints[name] }))
    writeGlyphsUts(mapping)
  }

  const pyPath = writeSubsetPython(codepoints)
  const py = spawnSync('python', [pyPath], { encoding: 'utf8' })
  fs.unlinkSync(pyPath)
  if (py.status !== 0) {
    console.error(py.stdout)
    console.error(py.stderr)
    throw new Error('font subset failed; ensure fontTools is installed: pip install fonttools')
  }
  console.log(py.stdout.trim())

  const b64 = fs.readFileSync(base64Path, 'utf8').trim()
  injectBase64IntoUvue(b64)
  patchUvueDocs()

  console.log(`[nax-icon] mapped ${mapping.length} icons from Tabler`)
  console.log(`[nax-icon] subset ttf => ${path.join(staticDir, 'nax-icon.ttf')}`)
  console.log(`[nax-icon] base64 injected into ${uvuePath}`)

  // cleanup intermediate full font (do not ship ~3MB source)
  const sourceTtfCleanup = path.join(staticDir, 'nax-icon.source.ttf')
  if (fs.existsSync(sourceTtfCleanup)) fs.unlinkSync(sourceTtfCleanup)
}


main()
