/**
 * Build nax-icon glyph map from Lucide official font codepoints.
 *
 * Why official font:
 * Lucide SVG icons are stroke-based; naive SVG->font conversion often yields empty glyphs.
 * We ship Lucide font binary and map semantic nax names -> Lucide codepoints.
 *
 * Usage (inside uni_modules/nax-icon):
 *   npm install lucide-static@1.24.0 --no-save
 *   node scripts/build-icons.mjs
 *
 * Runtime package only needs:
 *   static/nax-icon.ttf
 *   icons/glyphs.uts
 *   icons/codepoints.json
 *   icons/mapping.json
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const root = path.resolve(__dirname, '..')

const catalogPath = path.join(root, 'assets', 'icons', 'catalog.json')
const staticDir = path.join(root, 'static')
const iconsDir = path.join(root, 'icons')
const glyphsPath = path.join(iconsDir, 'glyphs.uts')
const codepointsPath = path.join(iconsDir, 'codepoints.json')

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true })
}

function resolveLucideCodepoints() {
  const candidates = [
    path.join(root, 'node_modules', 'lucide-static', 'font', 'codepoints.json'),
    path.join(process.cwd(), 'node_modules', 'lucide-static', 'font', 'codepoints.json')
  ]
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate
    }
  }
  return null
}

function resolveLucideFont(ext) {
  const candidates = [
    path.join(root, 'node_modules', 'lucide-static', 'font', `lucide.${ext}`),
    path.join(process.cwd(), 'node_modules', 'lucide-static', 'font', `lucide.${ext}`)
  ]
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate
    }
  }
  return null
}

function toUtsGlyph(codepoint) {
  return `\\u${codepoint.toString(16).toLowerCase().padStart(4, '0')}`
}

function writeGlyphsUts(mapping) {
  // Prefer plain if-chain for uni-app x / UTS compatibility (avoid Map runtime issues).
  const lines = []
  lines.push('/**')
  lines.push(' * Auto-generated by scripts/build-icons.mjs')
  lines.push(' * Source: Lucide official font (ISC) subset mapping for nax-ui')
  lines.push(' * Do not edit by hand. Re-run: node scripts/build-icons.mjs')
  lines.push(' */')
  lines.push('')
  lines.push('export function getNaxIconGlyph(name : string) : string {')
  for (const item of mapping) {
    lines.push(`\tif (name == '${item.name}') {`)
    lines.push(`\t\treturn '${toUtsGlyph(item.codepoint)}'`)
    lines.push('\t}')
  }
  lines.push("\treturn ''")
  lines.push('}')
  lines.push('')
  lines.push('export function listNaxIconNames() : string[] {')
  lines.push('\treturn [')
  for (const item of mapping) {
    lines.push(`\t\t'${item.name}',`)
  }
  lines.push('\t]')
  lines.push('}')
  lines.push('')
  fs.writeFileSync(glyphsPath, lines.join('\n'), 'utf8')
}

function main() {
  if (!fs.existsSync(catalogPath)) {
    throw new Error(`Missing catalog: ${catalogPath}`)
  }

  const catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'))
  if (!Array.isArray(catalog) || catalog.length === 0) {
    throw new Error('catalog.json is empty')
  }

  const lucideCodepointsPath = resolveLucideCodepoints()
  if (lucideCodepointsPath == null) {
    throw new Error('lucide-static font/codepoints.json not found. Install lucide-static first.')
  }

  const lucideCodepoints = JSON.parse(fs.readFileSync(lucideCodepointsPath, 'utf8'))
  ensureDir(staticDir)
  ensureDir(iconsDir)

  const ttfSrc = resolveLucideFont('ttf')
  const woffSrc = resolveLucideFont('woff')
  if (ttfSrc == null) {
    throw new Error('lucide-static font/lucide.ttf not found')
  }
  fs.copyFileSync(ttfSrc, path.join(staticDir, 'nax-icon.ttf'))
  if (woffSrc != null) {
    fs.copyFileSync(woffSrc, path.join(staticDir, 'nax-icon.woff'))
  }

  const missing = []
  const codepoints = {}
  const mapping = []

  for (const item of catalog) {
    const name = String(item.name || '').trim()
    const lucide = String(item.lucide || '').trim()
    if (!name || !lucide) {
      throw new Error(`Invalid catalog item: ${JSON.stringify(item)}`)
    }
    if (lucideCodepoints[lucide] == null) {
      missing.push(`${name} <= ${lucide}`)
      continue
    }
    const cp = Number(lucideCodepoints[lucide])
    codepoints[name] = cp
    mapping.push({ name, lucide, codepoint: cp })
  }

  if (missing.length > 0) {
    throw new Error(`Missing Lucide codepoints:\n- ${missing.join('\n- ')}`)
  }

  fs.writeFileSync(codepointsPath, JSON.stringify(codepoints, null, 2) + '\n', 'utf8')
  fs.writeFileSync(path.join(iconsDir, 'mapping.json'), JSON.stringify(mapping, null, 2) + '\n', 'utf8')
  writeGlyphsUts(mapping)

  console.log(`[nax-icon] mapped ${mapping.length} icons from Lucide font`)
  console.log(`[nax-icon] ttf => ${path.join(staticDir, 'nax-icon.ttf')}`)
  console.log(`[nax-icon] glyphs => ${glyphsPath}`)
  console.log('[nax-icon] note: current package ships full Lucide font binary; subset later if needed')
}

main()