/**
 * Build nax-icon assets:
 * 1) map Lucide codepoints from catalog
 * 2) copy Lucide font then subset to mapped glyphs
 * 3) emit base64 and rewrite @font-face in nax-icon.uvue
 *
 * Usage:
 *   pip/python with fontTools
 *   npm install --no-save lucide-static@1.24.0   (optional if font already present)
 *   node scripts/build-icons.mjs
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const root = path.resolve(__dirname, '..')

const catalogPath = path.join(root, 'assets', 'icons', 'catalog.json')
const staticDir = path.join(root, 'static')
const iconsDir = path.join(root, 'icons')
const glyphsPath = path.join(iconsDir, 'glyphs.uts')
const codepointsPath = path.join(iconsDir, 'codepoints.json')
const uvuePath = path.join(root, 'components', 'nax-icon', 'nax-icon.uvue')
const base64Path = path.join(staticDir, 'nax-icon.base64.txt')

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true })
}

function resolveLucideCodepoints() {
  const candidates = [
    path.join(root, 'node_modules', 'lucide-static', 'font', 'codepoints.json'),
    path.join(process.cwd(), 'node_modules', 'lucide-static', 'font', 'codepoints.json')
  ]
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate
  }
  return null
}

function resolveLucideFont(ext) {
  const candidates = [
    path.join(root, 'node_modules', 'lucide-static', 'font', `lucide.${ext}`),
    path.join(process.cwd(), 'node_modules', 'lucide-static', 'font', `lucide.${ext}`),
    path.join(staticDir, `nax-icon.${ext}`)
  ]
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate
  }
  return null
}

function toUtsGlyph(codepoint) {
  return `\\u${codepoint.toString(16).toLowerCase().padStart(4, '0')}`
}

function writeGlyphsUts(mapping) {
  const lines = []
  lines.push('/**')
  lines.push(' * Auto-generated by scripts/build-icons.mjs')
  lines.push(' * Source: Lucide official font (ISC) subset mapping for nax-ui')
  lines.push(' * Do not edit by hand. Re-run: node scripts/build-icons.mjs')
  lines.push(' */')
  lines.push('')
  lines.push('export function getNaxIconGlyph(name : string) : string {')
  for (const item of mapping) {
    lines.push(`\tif (name == '${item.name}') {`)
    lines.push(`\t\treturn '${toUtsGlyph(item.codepoint)}'`)
    lines.push('\t}')
  }
  lines.push("\treturn ''")
  lines.push('}')
  lines.push('')
  lines.push('export function listNaxIconNames() : string[] {')
  lines.push('\treturn [')
  for (const item of mapping) {
    lines.push(`\t\t'${item.name}',`)
  }
  lines.push('\t]')
  lines.push('}')
  lines.push('')
  fs.writeFileSync(glyphsPath, lines.join('\n'), 'utf8')
}

function writeSubsetPython(codepoints) {
  const pyPath = path.join(staticDir, '_subset_tmp.py')
  const unicodes = [0x20, ...Object.values(codepoints)]
  const code = `
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.subset import Subsetter, Options
import base64

root = Path(r'''${root.replace(/\\/g, '\\\\')}''')
src = root / 'static' / 'nax-icon.source.ttf'
if not src.exists():
    src = root / 'static' / 'nax-icon.ttf'
out_ttf = root / 'static' / 'nax-icon.ttf'
out_woff = root / 'static' / 'nax-icon.woff'
out_b64 = root / 'static' / 'nax-icon.base64.txt'
unicodes = ${JSON.stringify(unicodes)}

font = TTFont(str(src))
options = Options()
options.layout_features = ['*']
options.name_IDs = ['*']
options.name_languages = ['*']
options.notdef_outline = True
options.recommended_glyphs = True
options.recalc_bounds = True
options.recalc_timestamp = False
subsetter = Subsetter(options=options)
subsetter.populate(unicodes=unicodes)
subsetter.subset(font)
# normalize vertical metrics: lucide win ascent can exceed UPM and shift web/mp glyphs
upm = font['head'].unitsPerEm
font['hhea'].ascent = upm
font['hhea'].descent = 0
font['hhea'].lineGap = 0
font['OS/2'].sTypoAscender = upm
font['OS/2'].sTypoDescender = 0
font['OS/2'].sTypoLineGap = 0
font['OS/2'].usWinAscent = upm
font['OS/2'].usWinDescent = 0
font['OS/2'].fsSelection |= 1 << 7
# center glyphs in em square (fix left/right optical bias like plus)
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
glyf = font['glyf']
hmtx = font['hmtx']
for gname in list(glyf.keys()):
    if gname == '.notdef':
        continue
    g = glyf[gname]
    if g.numberOfContours == 0 and not getattr(g, 'components', None):
        hmtx[gname] = (upm, 0)
        continue
    g.recalcBounds(glyf)
    xMin, yMin, xMax, yMax = g.xMin, g.yMin, g.xMax, g.yMax
    if xMax <= xMin or yMax <= yMin:
        hmtx[gname] = (upm, 0)
        continue
    dx = upm / 2 - (xMin + xMax) / 2
    dy = upm / 2 - (yMin + yMax) / 2
    pen = TTGlyphPen(glyf)
    tpen = TransformPen(pen, (1, 0, 0, 1, dx, dy))
    g.draw(tpen, glyf)
    new_g = pen.glyph()
    new_g.recalcBounds(glyf)
    glyf[gname] = new_g
    hmtx[gname] = (upm, int(round(new_g.xMin)))
font.flavor = None
font.save(str(out_ttf))
font.flavor = 'woff'
font.save(str(out_woff))
b64 = base64.b64encode(out_ttf.read_bytes()).decode('ascii')
out_b64.write_text(b64, encoding='ascii')
print('subset ttf', out_ttf.stat().st_size, 'b64', len(b64))
`
  fs.writeFileSync(pyPath, code, 'utf8')
  return pyPath
}

function injectBase64IntoUvue(b64) {
  if (!fs.existsSync(uvuePath)) {
    throw new Error(`Missing component: ${uvuePath}`)
  }
  let uvue = fs.readFileSync(uvuePath, 'utf8')
  const face = [
    '\t/*',
    '\t * base64 内联字体：兼容微信小程序（禁止本地字体路径）',
    '\t * uvue/Harmony: @font-face 仅支持 font-family + src',
    '\t */',
    '\t@font-face {',
    '\t\tfont-family: nax-icon;',
    `\t\tsrc: url('data:font/truetype;charset=utf-8;base64,${b64}') format('truetype');`,
    '\t}'
  ].join('\n')

  // Only rewrite style-block @font-face that declares nax-icon.
  // Do not use open /* ... */ across the file (would delete <script>).
  const re = /\t@font-face\s*\{[\s\S]*?font-family:\s*nax-icon;[\s\S]*?\t\}/
  // Prefer replacing comment + @font-face when the comment is immediately above.
  const reWithComment = /\t\/\*\s*\n\t \*[\s\S]*?\*\/\s*\n\t@font-face\s*\{[\s\S]*?font-family:\s*nax-icon;[\s\S]*?\t\}/
  if (reWithComment.test(uvue)) {
    uvue = uvue.replace(reWithComment, face)
  } else if (re.test(uvue)) {
    uvue = uvue.replace(re, face)
  } else {
    throw new Error('Cannot find @font-face block in nax-icon.uvue')
  }
  fs.writeFileSync(uvuePath, uvue, 'utf8')
}


function main() {
  if (!fs.existsSync(catalogPath)) {
    throw new Error(`Missing catalog: ${catalogPath}`)
  }
  const catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'))
  const lucideCodepointsPath = resolveLucideCodepoints()
  if (lucideCodepointsPath == null) {
    // allow rebuild from existing mapping if lucide not installed
    if (!fs.existsSync(codepointsPath)) {
      throw new Error('lucide-static not found and no existing codepoints.json')
    }
  }

  ensureDir(staticDir)
  ensureDir(iconsDir)

  let mapping = []
  let codepoints = {}

  if (lucideCodepointsPath != null) {
    const lucideCodepoints = JSON.parse(fs.readFileSync(lucideCodepointsPath, 'utf8'))
    const ttfSrc = resolveLucideFont('ttf')
    if (ttfSrc == null) throw new Error('lucide ttf not found')
    // keep source full font for subset input
    fs.copyFileSync(ttfSrc, path.join(staticDir, 'nax-icon.source.ttf'))
    fs.copyFileSync(ttfSrc, path.join(staticDir, 'nax-icon.ttf'))

    const missing = []
    for (const item of catalog) {
      const name = String(item.name || '').trim()
      const lucide = String(item.lucide || '').trim()
      if (lucideCodepoints[lucide] == null) {
        missing.push(`${name} <= ${lucide}`)
        continue
      }
      const cp = Number(lucideCodepoints[lucide])
      codepoints[name] = cp
      mapping.push({ name, lucide, codepoint: cp })
    }
    if (missing.length) throw new Error(`Missing Lucide codepoints:\n- ${missing.join('\n- ')}`)
    fs.writeFileSync(codepointsPath, JSON.stringify(codepoints, null, 2) + '\n', 'utf8')
    fs.writeFileSync(path.join(iconsDir, 'mapping.json'), JSON.stringify(mapping, null, 2) + '\n', 'utf8')
    writeGlyphsUts(mapping)
  } else {
    codepoints = JSON.parse(fs.readFileSync(codepointsPath, 'utf8'))
    mapping = Object.keys(codepoints).map((name) => ({ name, codepoint: codepoints[name] }))
    writeGlyphsUts(mapping)
  }

  const pyPath = writeSubsetPython(codepoints)
  const py = spawnSync('python', [pyPath], { encoding: 'utf8' })
  fs.unlinkSync(pyPath)
  if (py.status !== 0) {
    console.error(py.stdout)
    console.error(py.stderr)
    throw new Error('font subset failed; ensure fontTools is installed: pip install fonttools')
  }
  console.log(py.stdout.trim())

  const b64 = fs.readFileSync(base64Path, 'utf8').trim()
  injectBase64IntoUvue(b64)

  // cleanup intermediate source if present
  const sourceTtf = path.join(staticDir, 'nax-icon.source.ttf')
  if (fs.existsSync(sourceTtf)) fs.unlinkSync(sourceTtf)

  console.log(`[nax-icon] mapped ${mapping.length} icons`)
  console.log(`[nax-icon] subset ttf => ${path.join(staticDir, 'nax-icon.ttf')}`)
  console.log(`[nax-icon] base64 injected into ${uvuePath}`)
}

main()
