export default [
  {
    heading: '基础（附近 / 排序 / 价格）',
    body: "```uvue\n<nax-dropdown border-bottom @open=\"onOpen\" @close=\"onClose\" @change=\"onMenuChange\">\n\t<nax-dropdown-item\n\t\tv-model=\"nearValue\"\n\t\ttitle=\"附近\"\n\t\t:options=\"nearOptions\"\n\t\t@change=\"onNearChange\"\n\t></nax-dropdown-item>\n\t<nax-dropdown-item v-model=\"sortValue\" title=\"排序\" :options=\"sortOptions\"></nax-dropdown-item>\n\t<nax-dropdown-item v-model=\"priceValue\" title=\"价格\" :options=\"priceOptions\" display-selected></nax-dropdown-item>\n</nax-dropdown>\n```\n\n```uts\nconst nearValue = ref('1')\nconst sortValue = ref('default')\nconst priceValue = ref('')\n\nconst nearOptions = [\n\t{ label: '附近', value: '1' },\n\t{ label: '500m', value: '2' },\n\t{ label: '1km', value: '3' },\n\t{ label: '3km', value: '4' }\n]\n\nconst sortOptions = [\n\t{ label: '智能排序', value: 'default' },\n\t{ label: '距离优先', value: 'distance' },\n\t{ label: '好评优先', value: 'rate' },\n\t{ label: '销量优先', value: 'sales' }\n]\n\nconst priceOptions = [\n\t{ label: '不限', value: '' },\n\t{ label: '0-50', value: '0-50' },\n\t{ label: '50-100', value: '50-100' },\n\t{ label: '100 以上', value: '100+' }\n]\n\nfunction onOpen(index : number) {\n\t// 打开第 index 个菜单\n}\n\nfunction onClose(index : number) {\n\t// 关闭第 index 个菜单\n}\n\nfunction onMenuChange(index : number) {\n\t// 切换菜单\n}\n\nfunction onNearChange(value : string) {\n\t// value：选中值\n}\n```"
  },
  {
    heading: '自定义面板 + 手动关闭',
    body: "dropdown-item 默认插槽自定义面板内容，ref 手动关闭弹层。\n\n```uvue\n<nax-dropdown ref=\"filterDropdown\" border-bottom border-radius=\"12\">\n\t<nax-dropdown-item title=\"筛选\" :highlighted=\"filterActive\">\n\t\t<view class=\"filter-panel\">\n\t\t\t<text>仅看包邮</text>\n\t\t\t<nax-switch v-model=\"onlyFreeShip\"></nax-switch>\n\t\t</view>\n\t\t<view class=\"filter-panel\">\n\t\t\t<text>仅看有货</text>\n\t\t\t<nax-switch v-model=\"onlyInStock\"></nax-switch>\n\t\t</view>\n\t\t<view class=\"filter-actions\">\n\t\t\t<nax-button size=\"sm\" label=\"重置\" @click=\"resetFilter\"></nax-button>\n\t\t\t<nax-button size=\"sm\" type=\"primary\" label=\"确定\" @click=\"confirmFilter\"></nax-button>\n\t\t</view>\n\t</nax-dropdown-item>\n\t<nax-dropdown-item v-model=\"brandValue\" title=\"品牌\" :options=\"brandOptions\" height=\"200\"></nax-dropdown-item>\n</nax-dropdown>\n```\n\n```uts\ntype NaxDropdownExpose = {\n\topen : (index : number) => void\n\tclose : () => void\n}\nconst filterDropdown = ref(null as NaxDropdownExpose | null)\n\nconst onlyFreeShip = ref(false)\nconst onlyInStock = ref(false)\nconst filterActive = ref(false)\nconst brandValue = ref('')\n\nconst brandOptions = [\n\t{ label: '全部品牌', value: '' },\n\t{ label: '品牌 A', value: 'a' },\n\t{ label: '品牌 B', value: 'b' },\n\t{ label: '品牌 C', value: 'c' },\n\t{ label: '品牌 D', value: 'd' },\n\t{ label: '品牌 E', value: 'e' },\n\t{ label: '品牌 F', value: 'f' },\n\t{ label: '品牌 G', value: 'g' }\n]\n\nfunction resetFilter() {\n\tonlyFreeShip.value = false\n\tonlyInStock.value = false\n\tfilterActive.value = false\n}\n\nfunction confirmFilter() {\n\tfilterActive.value = onlyFreeShip.value || onlyInStock.value\n\tif (filterDropdown.value != null) {\n\t\tfilterDropdown.value.close()\n\t}\n}\n```"
  },
  {
    heading: '尺寸 size / 禁用项',
    body: "```uvue\n<nax-dropdown size=\"sm\" border-bottom>\n\t<nax-dropdown-item v-model=\"sizeValue\" title=\"小号\" :options=\"sizeOptions\"></nax-dropdown-item>\n\t<nax-dropdown-item title=\"禁用\" disabled :options=\"sizeOptions\"></nax-dropdown-item>\n</nax-dropdown>\n\n<nax-dropdown size=\"lg\" border-bottom>\n\t<nax-dropdown-item v-model=\"sizeValue\" title=\"大号\" :options=\"sizeOptions\"></nax-dropdown-item>\n\t<nax-dropdown-item v-model=\"sizeValue2\" title=\"大号2\" :options=\"sizeOptions\"></nax-dropdown-item>\n</nax-dropdown>\n```\n\n```uts\nconst sizeValue = ref('a')\nconst sizeValue2 = ref('b')\n\nconst sizeOptions = [\n\t{ label: '选项 A', value: 'a' },\n\t{ label: '选项 B', value: 'b' },\n\t{ label: '选项 C', value: 'c' }\n]\n```"
  },
  {
    heading: '命令式 open / close',
    body: "通过 ref 调用 open(index) / close() 控制弹层。\n\n```uvue\n<nax-button size=\"sm\" label=\"打开第 0 项\" @click=\"openFirst\"></nax-button>\n<nax-button size=\"sm\" label=\"关闭\" @click=\"closeCmd\"></nax-button>\n\n<nax-dropdown ref=\"cmdDropdown\" border-bottom>\n\t<nax-dropdown-item v-model=\"cmdValue\" title=\"命令式\" :options=\"nearOptions\"></nax-dropdown-item>\n\t<nax-dropdown-item v-model=\"cmdValue2\" title=\"第二项\" :options=\"sortOptions\"></nax-dropdown-item>\n</nax-dropdown>\n```\n\n```uts\ntype NaxDropdownExpose = {\n\topen : (index : number) => void\n\tclose : () => void\n}\nconst cmdDropdown = ref(null as NaxDropdownExpose | null)\nconst cmdValue = ref('')\nconst cmdValue2 = ref('')\n\nfunction openFirst() {\n\tif (cmdDropdown.value != null) {\n\t\tcmdDropdown.value.open(0)\n\t}\n}\n\nfunction closeCmd() {\n\tif (cmdDropdown.value != null) {\n\t\tcmdDropdown.value.close()\n\t}\n}\n```"
  }
]
