export default [
  {
    heading: '基础分页加载',
    body: "```uvue\n<nax-list\n\t:key=\"key\"\n\theight=\"360px\"\n\t:loading=\"loading\"\n\t:finished=\"finished\"\n\t:error=\"error\"\n\t:empty=\"empty\"\n\t@load=\"onLoad\"\n\t@click-error=\"resetList\"\n>\n\t<template #header>\n\t\t<text class=\"list-header\">已加载 {{ list.length }} 条</text>\n\t</template>\n\t<nax-cell\n\t\tv-for=\"(title, index) in list\"\n\t\t:key=\"index\"\n\t\t:title=\"title\"\n\t\t:value=\"'' + (index + 1)\"\n\t\tis-link\n\t></nax-cell>\n</nax-list>\n<nax-button size=\"sm\" label=\"重置列表\" @click=\"resetList\"></nax-button>\n```\n\n```uts\nconst list = ref([] as string[])\nconst loading = ref(false)\nconst finished = ref(false)\nconst error = ref(false)\nconst loaded = ref(false)\nconst key = ref(0)\nconst PAGE_SIZE = 10\nconst TOTAL = 35\n\nconst empty = computed((): boolean => {\n\treturn loaded.value && list.value.length == 0 && !loading.value\n})\n\nfunction onLoad() {\n\tif (loading.value || finished.value) {\n\t\treturn\n\t}\n\tloading.value = true\n\terror.value = false\n\tsetTimeout(() => {\n\t\tconst start = list.value.length\n\t\tconst next = [] as string[]\n\t\tvar i = 0\n\t\twhile (i < PAGE_SIZE && start + i < TOTAL) {\n\t\t\tnext.push('列表项 ' + (start + i + 1).toString())\n\t\t\ti++\n\t\t}\n\t\tlist.value = list.value.concat(next)\n\t\tloaded.value = true\n\t\tloading.value = false\n\t\tif (list.value.length >= TOTAL || next.length == 0) {\n\t\t\tfinished.value = true\n\t\t}\n\t}, 600)\n}\n\nfunction resetList() {\n\tlist.value = [] as string[]\n\tloading.value = false\n\tfinished.value = false\n\terror.value = false\n\tloaded.value = false\n\tkey.value = key.value + 1\n}\n```"
  },
  {
    heading: '下拉刷新 + 加载更多',
    body: "```uvue\n<nax-list\n\t:key=\"rfKey\"\n\theight=\"320px\"\n\t:enable-refresh=\"true\"\n\t:refreshing=\"rfRefreshing\"\n\t:loading=\"rfLoading\"\n\t:finished=\"rfFinished\"\n\t:error=\"rfError\"\n\t:empty=\"rfEmpty\"\n\t@refresh=\"onRfRefresh\"\n\t@update:refreshing=\"onRfRefreshing\"\n\t@load=\"onRfLoad\"\n>\n\t<template #header>\n\t\t<text class=\"list-header\">刷新批次 #{{ rfBatch }} · {{ rfList.length }} 条</text>\n\t</template>\n\t<nax-cell\n\t\tv-for=\"(title, index) in rfList\"\n\t\t:key=\"index\"\n\t\t:title=\"title\"\n\t\t:label=\"index == 0 ? '下拉可刷新' : ''\"\n\t></nax-cell>\n</nax-list>\n```\n\n```uts\nconst rfList = ref([] as string[])\nconst rfLoading = ref(false)\nconst rfFinished = ref(false)\nconst rfError = ref(false)\nconst rfRefreshing = ref(false)\nconst rfLoaded = ref(false)\nconst rfPage = ref(0)\nconst rfBatch = ref(1)\nconst rfKey = ref(0)\nconst RF_TOTAL = 28\n\nconst rfEmpty = computed((): boolean => {\n\treturn rfLoaded.value && rfList.value.length == 0 && !rfLoading.value && !rfRefreshing.value\n})\n\nfunction onRfRefreshing(val : boolean) {\n\trfRefreshing.value = val\n}\n\nfunction onRfRefresh() {\n\trfRefreshing.value = true\n\trfError.value = false\n\tsetTimeout(() => {\n\t\t// 重新拉第一页，批次 +1\n\t\trfBatch.value = rfBatch.value + 1\n\t\trfList.value = [] as string[]\n\t\trfPage.value = 0\n\t\tloadPage()\n\t}, 800)\n}\n\nfunction onRfLoad() {\n\tloadPage()\n}\n\nfunction loadPage() {\n\tif (rfLoading.value || rfFinished.value || rfRefreshing.value) {\n\t\treturn\n\t}\n\trfLoading.value = true\n\trfError.value = false\n\tsetTimeout(() => {\n\t\tconst start = rfList.value.length\n\t\tconst next = [] as string[]\n\t\tvar i = 0\n\t\twhile (i < 10 && start + i < RF_TOTAL) {\n\t\t\tnext.push('B' + rfBatch.value.toString() + ' · 条目 ' + (start + i + 1).toString())\n\t\t\ti++\n\t\t}\n\t\trfList.value = rfList.value.concat(next)\n\t\trfPage.value = rfPage.value + 1\n\t\trfLoaded.value = true\n\t\trfLoading.value = false\n\t\trfRefreshing.value = false\n\t\tif (rfList.value.length >= RF_TOTAL || next.length == 0) {\n\t\t\trfFinished.value = true\n\t\t}\n\t}, 500)\n}\n```"
  },
  {
    heading: '空状态',
    body: "```uvue\n<nax-list height=\"220px\" :empty=\"true\" empty-text=\"暂无订单\" empty-icon=\"notes-off\">\n</nax-list>\n```\n\nempty=true 时展示 nax-empty（默认 notes-off）。"
  },
  {
    heading: '错误重试',
    body: "```uvue\n<nax-list\n\t:key=\"errKey\"\n\theight=\"220px\"\n\t:loading=\"errLoading\"\n\t:finished=\"errFinished\"\n\t:error=\"errError\"\n\t:empty=\"false\"\n\t@load=\"onErrLoad\"\n>\n\t<nax-cell\n\t\tv-for=\"(title, index) in errList\"\n\t\t:key=\"index\"\n\t\t:title=\"title\"\n\t></nax-cell>\n</nax-list>\n<nax-button size=\"sm\" label=\"重置为失败流\" @click=\"resetErr\"></nax-button>\n```\n\n```uts\nconst errList = ref([] as string[])\nconst errLoading = ref(false)\nconst errFinished = ref(false)\nconst errError = ref(false)\nconst errAttempt = ref(0)\nconst errKey = ref(0)\n\nfunction onErrLoad() {\n\tif (errLoading.value || errFinished.value) {\n\t\treturn\n\t}\n\terrLoading.value = true\n\terrError.value = false\n\terrAttempt.value = errAttempt.value + 1\n\tconst attempt = errAttempt.value\n\tsetTimeout(() => {\n\t\t// 前两次失败，第三次成功并 finished\n\t\tif (attempt < 3) {\n\t\t\terrLoading.value = false\n\t\t\terrError.value = true\n\t\t\treturn\n\t\t}\n\t\terrList.value = ['恢复后的条目 A', '恢复后的条目 B'] as string[]\n\t\terrLoading.value = false\n\t\terrFinished.value = true\n\t}, 500)\n}\n\nfunction resetErr() {\n\terrList.value = [] as string[]\n\terrLoading.value = false\n\terrFinished.value = false\n\terrError.value = false\n\terrAttempt.value = 0\n\terrKey.value = errKey.value + 1\n}\n```"
  },
  {
    heading: '自定义空态 / 底态',
    body: "```uvue\n<nax-list height=\"200px\" :empty=\"true\">\n\t<template #empty>\n\t\t<nax-empty icon=\"search\" description=\"换个关键词试试\">\n\t\t\t<template #action>\n\t\t\t\t<nax-button size=\"sm\" type=\"primary\" label=\"清空筛选\" @click=\"onClearFilter\"></nax-button>\n\t\t\t</template>\n\t\t</nax-empty>\n\t</template>\n</nax-list>\n```\n\n```uts\nfunction onClearFilter() {\n\t// 清空筛选后重新加载\n}\n```"
  }
]
