export default [
	{
		heading: '弹出位置 position',
		body: "```uvue\n<nax-button type=\"primary\" label=\"底部 bottom\" @click=\"openAt('bottom')\"></nax-button>\n<nax-button label=\"中间 center\" @click=\"openAt('center')\"></nax-button>\n<nax-button label=\"左侧 left\" @click=\"openAt('left')\"></nax-button>\n<nax-button label=\"右侧 right\" @click=\"openAt('right')\"></nax-button>\n\n<nax-picker v-model:show=\"mainShow\" :position=\"mainPosition\">\n\t<view class=\"panel\">\n\t\t<text class=\"panel__title\">{{ positionTitle }}</text>\n\t\t<text class=\"panel__desc\">position = {{ mainPosition }}</text>\n\t\t<nax-button type=\"primary\" label=\"完成\" @click=\"mainShow = false\"></nax-button>\n\t</view>\n</nax-picker>\n```\n\n```uts\nconst mainShow = ref(false)\nconst mainPosition = ref('bottom')\n\nconst positionTitle = computed((): string => {\n\tif (mainPosition.value == 'center') {\n\t\treturn '中间弹出'\n\t}\n\tif (mainPosition.value == 'left') {\n\t\treturn '左侧抽屉'\n\t}\n\tif (mainPosition.value == 'right') {\n\t\treturn '右侧抽屉'\n\t}\n\treturn '底部弹出'\n})\n\nfunction openAt(pos : string) {\n\tmainPosition.value = pos\n\tmainShow.value = true\n}\n```"
	},
	{
		heading: '行为',
		body: "```uvue\n<nax-button size=\"sm\" label=\"禁止点遮罩关闭\" @click=\"openMaskLocked\"></nax-button>\n<nax-button size=\"sm\" label=\"无圆角\" @click=\"openNoRound\"></nax-button>\n<nax-button size=\"sm\" label=\"自定义宽高（右侧 60%）\" @click=\"openCustomSize\"></nax-button>\n\n<nax-picker v-model:show=\"lockedShow\" position=\"center\" :mask-closable=\"false\">\n\t<text class=\"panel__title\">不可点遮罩关闭</text>\n\t<nax-button type=\"primary\" label=\"知道了\" @click=\"lockedShow = false\"></nax-button>\n</nax-picker>\n\n<nax-picker v-model:show=\"noRoundShow\" position=\"bottom\" :round=\"false\">\n\t<text class=\"panel__title\">无圆角底部面板</text>\n\t<nax-button label=\"关闭\" @click=\"noRoundShow = false\"></nax-button>\n</nax-picker>\n\n<nax-picker v-model:show=\"sizeShow\" position=\"right\" width=\"60%\">\n\t<text class=\"panel__title\">宽 60% 侧栏</text>\n\t<nax-button type=\"primary\" label=\"关闭\" @click=\"sizeShow = false\"></nax-button>\n</nax-picker>\n```\n\n```uts\nconst lockedShow = ref(false)\nconst noRoundShow = ref(false)\nconst sizeShow = ref(false)\n\nfunction openMaskLocked() {\n\tlockedShow.value = true\n}\n\nfunction openNoRound() {\n\tnoRoundShow.value = true\n}\n\nfunction openCustomSize() {\n\tsizeShow.value = true\n}\n```"
	}
]
