export default [
  {
    heading: '基础用法',
    body: "```uvue\n<nax-upload\n\t:file-list=\"basicList\"\n\t:max-count=\"6\"\n\tmultiple\n\tname=\"basic\"\n\t@after-read=\"onBasicAfterRead\"\n\t@delete=\"onBasicDelete\"\n\t@oversize=\"onOversize\"\n></nax-upload>\n```\n\n```uts\nconst basicList = ref([] as any[])\n\nfunction onBasicAfterRead(e : any) {\n\t// 选择完成：从 e.files（或 e.file）取文件追加到列表\n\tbasicList.value = appendFiles(basicList.value, e)\n}\n\nfunction onBasicDelete(e : any) {\n\tbasicList.value = applyDelete(basicList.value, e)\n}\n\nfunction onOversize(_e : any) {\n\tuni.showToast({\n\t\ttitle: '文件过大',\n\t\ticon: 'none'\n\t})\n}\n\n// 通用工具：合并 after-read 文件（App UTS 不能对 any 访问 .value）\nfunction appendFiles(list : any[], e : any) : any[] {\n\tconst payload = e as UTSJSONObject\n\tconst files = payload.getArray('files')\n\tconst next = cloneList(list)\n\tif (files != null) {\n\t\tvar i = 0\n\t\twhile (i < files.length) {\n\t\t\tnext.push(files[i] as any)\n\t\t\ti++\n\t\t}\n\t} else {\n\t\tconst file = payload.getAny('file')\n\t\tif (file != null) {\n\t\t\tnext.push(file)\n\t\t}\n\t}\n\treturn next\n}\n\n// 通用工具：删除项（e.fileList 优先，否则按 e.index）\nfunction applyDelete(list : any[], e : any) : any[] {\n\tconst payload = e as UTSJSONObject\n\tconst next = payload.getArray('fileList')\n\tif (next != null) {\n\t\treturn next as any[]\n\t}\n\tconst idx = payload.getNumber('index')\n\tif (idx == null) {\n\t\treturn list\n\t}\n\tconst out = [] as any[]\n\tvar i = 0\n\twhile (i < list.length) {\n\t\tif (i != idx) {\n\t\t\tout.push(list[i])\n\t\t}\n\t\ti++\n\t}\n\treturn out\n}\n\nfunction cloneList(list : any[]) : any[] {\n\tconst out = [] as any[]\n\tvar i = 0\n\twhile (i < list.length) {\n\t\tout.push(list[i])\n\t\ti++\n\t}\n\treturn out\n}\n```"
  },
  {
    heading: '限制数量 maxCount=3',
    body: "```uvue\n<nax-upload\n\t:file-list=\"limitList\"\n\t:max-count=\"3\"\n\tmultiple\n\tupload-text=\"上传\"\n\t@after-read=\"onLimitAfterRead\"\n\t@delete=\"onLimitDelete\"\n></nax-upload>\n```\n\n```uts\nconst limitList = ref([] as any[])\n\nfunction onLimitAfterRead(e : any) {\n\tlimitList.value = appendFiles(limitList.value, e)\n}\n\nfunction onLimitDelete(e : any) {\n\tlimitList.value = applyDelete(limitList.value, e)\n}\n\n// appendFiles / applyDelete 见「基础用法」\n```"
  },
  {
    heading: '状态展示（uploading / failed / success）',
    body: "```uvue\n<nax-upload\n\t:file-list=\"statusList\"\n\t:max-count=\"4\"\n\t:deletable=\"true\"\n\t@delete=\"onStatusDelete\"\n></nax-upload>\n```\n\n```uts\nconst statusList = ref([\n\t{\n\t\turl: 'https://qiniu-web-assets.dcloud.net.cn/unidoc/zh/shuijiao.jpg',\n\t\tstatus: 'uploading',\n\t\tmessage: '上传中',\n\t\ttype: 'image'\n\t} as UTSJSONObject,\n\t{\n\t\turl: 'https://qiniu-web-assets.dcloud.net.cn/unidoc/zh/shuijiao.jpg',\n\t\tstatus: 'failed',\n\t\tmessage: '失败',\n\t\ttype: 'image'\n\t} as UTSJSONObject,\n\t{\n\t\turl: 'https://qiniu-web-assets.dcloud.net.cn/unidoc/zh/shuijiao.jpg',\n\t\tstatus: 'success',\n\t\tmessage: '',\n\t\ttype: 'image'\n\t} as UTSJSONObject\n] as any[])\n\nfunction onStatusDelete(e : any) {\n\tstatusList.value = applyDelete(statusList.value, e)\n}\n```"
  },
  {
    heading: '禁用 disabled',
    body: "```uvue\n<nax-upload :file-list=\"disabledList\" disabled :max-count=\"4\"></nax-upload>\n```\n\n```uts\nconst disabledList = ref([\n\t{\n\t\turl: 'https://qiniu-web-assets.dcloud.net.cn/unidoc/zh/shuijiao.jpg',\n\t\tstatus: 'success',\n\t\tmessage: '',\n\t\ttype: 'image'\n\t} as UTSJSONObject\n] as any[])\n```"
  },
  {
    heading: '自定义尺寸 / 不可删除',
    body: "```uvue\n<nax-upload\n\t:file-list=\"sizeList\"\n\twidth=\"100\"\n\theight=\"100\"\n\t:deletable=\"false\"\n\t:max-count=\"4\"\n\t@after-read=\"onSizeAfterRead\"\n></nax-upload>\n```\n\n```uts\nconst sizeList = ref([] as any[])\n\nfunction onSizeAfterRead(e : any) {\n\tsizeList.value = appendFiles(sizeList.value, e)\n}\n```"
  },
  {
    heading: '自定义添加按钮（slot）',
    body: "```uvue\n<nax-upload\n\t:file-list=\"slotList\"\n\t:max-count=\"5\"\n\t@after-read=\"onSlotAfterRead\"\n\t@delete=\"onSlotDelete\"\n>\n\t<view class=\"custom-add\">\n\t\t<nax-icon name=\"image\" size=\"lg\" color=\"#18a058\"></nax-icon>\n\t\t<text class=\"custom-add__text\">添加图片</text>\n\t</view>\n</nax-upload>\n```\n\n```uts\nconst slotList = ref([] as any[])\n\nfunction onSlotAfterRead(e : any) {\n\tslotList.value = appendFiles(slotList.value, e)\n}\n\nfunction onSlotDelete(e : any) {\n\tslotList.value = applyDelete(slotList.value, e)\n}\n```"
  },
  {
    heading: '自动上传 autoUpload',
    body: "```uvue\n<nax-upload\n\t:file-list=\"autoList\"\n\tauto-upload\n\t:action=\"uploadAction\"\n\t:max-count=\"4\"\n\tmultiple\n\tname=\"file\"\n\t@update:file-list=\"onAutoFileList\"\n\t@after-read=\"onAutoAfterRead\"\n\t@success=\"onAutoSuccess\"\n\t@fail=\"onAutoFail\"\n\t@delete=\"onAutoDelete\"\n></nax-upload>\n```\n\n```uts\nconst autoList = ref([] as any[])\nconst uploadAction = ref('https://your-server.com/upload')\nconst autoEvent = ref('等待自动上传')\n\nfunction onAutoFileList(list : any) {\n\tif (list == null) {\n\t\tautoList.value = [] as any[]\n\t\treturn\n\t}\n\tautoList.value = list as any[]\n}\n\nfunction onAutoAfterRead(_e : any) {\n\tautoEvent.value = 'afterRead（随后自动上传）'\n}\n\nfunction onAutoSuccess(e : any) {\n\tconst payload = e as UTSJSONObject\n\tconst url = payload.getString('url')\n\tautoEvent.value = 'success: ' + (url != null ? url : '')\n}\n\nfunction onAutoFail(_e : any) {\n\tautoEvent.value = 'fail: 上传失败'\n}\n\nfunction onAutoDelete(e : any) {\n\tautoList.value = applyDelete(autoList.value, e)\n}\n```"
  },
  {
    heading: '模拟上传进度',
    body: "```uvue\n<nax-upload\n\t:file-list=\"mockList\"\n\t:max-count=\"6\"\n\tmultiple\n\t@after-read=\"onMockAfterRead\"\n\t@delete=\"onMockDelete\"\n></nax-upload>\n```\n\n```uts\nconst mockList = ref([] as any[])\n\nfunction onMockAfterRead(e : any) {\n\t// 先把新文件置为 uploading，再模拟异步上传成功\n\tconst payload = e as UTSJSONObject\n\tconst files = payload.getArray('files')\n\tif (files == null) {\n\t\treturn\n\t}\n\tconst next = [] as any[]\n\tvar i = 0\n\twhile (i < files.length) {\n\t\tconst raw = files[i] as UTSJSONObject\n\t\tconst url = raw.getString('url')\n\t\tnext.push({\n\t\t\turl: url != null ? url : '',\n\t\t\tthumb: url != null ? url : '',\n\t\t\ttype: 'image',\n\t\t\tstatus: 'uploading',\n\t\t\tmessage: '上传中'\n\t\t} as UTSJSONObject)\n\t\ti++\n\t}\n\tconst start = mockList.value.length\n\tconst merged = cloneList(mockList.value)\n\tvar j = 0\n\twhile (j < next.length) {\n\t\tmerged.push(next[j])\n\t\tj++\n\t}\n\tmockList.value = merged\n\n\t// 模拟异步上传完成\n\tconst end = merged.length\n\tsetTimeout(() => {\n\t\tconst cur = cloneList(mockList.value)\n\t\tvar k = start\n\t\twhile (k < end && k < cur.length) {\n\t\t\tconst it = cur[k] as UTSJSONObject\n\t\t\tconst u = it.getString('url')\n\t\t\tcur[k] = {\n\t\t\t\turl: u != null ? u : '',\n\t\t\t\tthumb: u != null ? u : '',\n\t\t\t\ttype: 'image',\n\t\t\t\tstatus: 'success',\n\t\t\t\tmessage: ''\n\t\t\t} as UTSJSONObject\n\t\t\tk++\n\t\t}\n\t\tmockList.value = cur\n\t}, 1200)\n}\n\nfunction onMockDelete(e : any) {\n\tmockList.value = applyDelete(mockList.value, e)\n}\n```"
  }
]
