export default [
  {
    heading: '5000 条 · 窗口裁剪',
    body: "```uvue\n<nax-virtual-list\n\tref=\"basicRef\"\n\theight=\"420px\"\n\t:list=\"basicList\"\n\t:item-height=\"52\"\n\t:buffer=\"10\"\n\tkey-field=\"id\"\n\t@visible-change=\"onVisibleChange\"\n\t@click=\"onRowClick\"\n>\n\t<template #default=\"{ item, index }\">\n\t\t<nax-cell\n\t\t\t:title=\"readTitle(item)\"\n\t\t\t:value=\"indexLabel(index)\"\n\t\t\t:label=\"readSub(item)\"\n\t\t\tis-link\n\t\t></nax-cell>\n\t</template>\n</nax-virtual-list>\n\n<nax-button size=\"sm\" label=\"滚到 #2500\" @click=\"goIndex(2500)\"></nax-button>\n<nax-button size=\"sm\" type=\"primary\" label=\"滚到末尾\" @click=\"goIndex(4999)\"></nax-button>\n```\n\n```uts\n// 简要 mock：5000 条固定行高数据\nfunction makeItem(id : number, prefix : string) : UTSJSONObject {\n\treturn {\n\t\tid: id,\n\t\ttitle: prefix + ' 行 #' + id.toString(),\n\t\tsub: '固定行高虚拟渲染 · id=' + id.toString()\n\t} as UTSJSONObject\n}\n\nconst basicList = ref([] as UTSJSONObject[])\nfunction buildBasic(count : number) {\n\tconst rows = [] as UTSJSONObject[]\n\tvar i = 0\n\twhile (i < count) {\n\t\trows.push(makeItem(i, 'Item'))\n\t\ti++\n\t}\n\tbasicList.value = rows\n}\nbuildBasic(5000)\n\n// 滚动到指定下标\nconst basicRef = ref(null)\nfunction goIndex(index : number) {\n\t// basicRef.value?.scrollToIndex(index)\n}\n\nfunction onVisibleChange(e : UTSJSONObject) {\n\t// 可视窗口变化：e.start / e.end\n}\n\nfunction onRowClick(e : UTSJSONObject) {\n\t// 点击行：e.index\n}\n\nfunction readTitle(item : any | null) : string {\n\tif (item == null) {\n\t\treturn ''\n\t}\n\tconst t = (item as UTSJSONObject)['title']\n\treturn t != null ? ('' + t) : ''\n}\n\nfunction readSub(item : any | null) : string {\n\tif (item == null) {\n\t\treturn ''\n\t}\n\tconst t = (item as UTSJSONObject)['sub']\n\treturn t != null ? ('' + t) : ''\n}\n\nfunction indexLabel(index : any | null) : string {\n\tconst i = index as number\n\treturn (i + 1).toString()\n}\n```"
  },
  {
    heading: '触底分页追加',
    body: "```uvue\n<nax-virtual-list\n\theight=\"360px\"\n\t:list=\"pageList\"\n\t:item-height=\"72\"\n\t:buffer=\"6\"\n\tkey-field=\"id\"\n\t:loading=\"pageLoading\"\n\t:finished=\"pageFinished\"\n\t:error=\"pageError\"\n\t@load=\"onPageLoad\"\n\t@click-error=\"onPageErrorClick\"\n>\n\t<template #header>\n\t\t<view class=\"list-header\">\n\t\t\t<text>已加载 {{ pageList.length }} 条</text>\n\t\t</view>\n\t</template>\n\t<template #default=\"{ item, index }\">\n\t\t<nax-cell\n\t\t\t:title=\"readTitle(item)\"\n\t\t\t:value=\"indexLabel(index)\"\n\t\t\t:label=\"readSub(item)\"\n\t\t\tis-link\n\t\t></nax-cell>\n\t</template>\n</nax-virtual-list>\n```\n\n```uts\nconst pageList = ref([] as UTSJSONObject[])\nconst pageLoading = ref(false)\nconst pageFinished = ref(false)\nconst pageError = ref(false)\nconst PAGE_SIZE = 30\nconst PAGE_MAX = 300\nlet pageSeed = 0\n\n// 初始自动 load · 每次滚到底部 +30 · 追加后保持当前位置\nfunction onPageLoad() {\n\tif (pageLoading.value || pageFinished.value) {\n\t\treturn\n\t}\n\tpageLoading.value = true\n\tpageError.value = false\n\t// 模拟接口：450ms 后追加一页\n\tsetTimeout(() => {\n\t\tconst next = [] as UTSJSONObject[]\n\t\tvar n = 0\n\t\twhile (n < PAGE_SIZE) {\n\t\t\tconst id = pageSeed\n\t\t\tpageSeed++\n\t\t\tnext.push(makeItem(id, 'Page'))\n\t\t\tn++\n\t\t}\n\t\tconst merged = [] as UTSJSONObject[]\n\t\tvar j = 0\n\t\tconst cur = pageList.value\n\t\twhile (j < cur.length) {\n\t\t\tmerged.push(cur[j])\n\t\t\tj++\n\t\t}\n\t\tvar k = 0\n\t\twhile (k < next.length) {\n\t\t\tmerged.push(next[k])\n\t\t\tk++\n\t\t}\n\t\tpageList.value = merged\n\t\tpageLoading.value = false\n\t\tif (pageList.value.length >= PAGE_MAX) {\n\t\t\tpageFinished.value = true\n\t\t}\n\t}, 450)\n}\n\nfunction onPageErrorClick() {\n\tpageError.value = false\n}\n```"
  },
  {
    heading: '下拉刷新',
    body: "```uvue\n<nax-virtual-list\n\theight=\"320px\"\n\t:list=\"rfList\"\n\t:item-height=\"48\"\n\t:buffer=\"6\"\n\tkey-field=\"id\"\n\t:enable-refresh=\"true\"\n\t:refreshing=\"rfRefreshing\"\n\t:loading=\"rfLoading\"\n\t:finished=\"rfFinished\"\n\t@refresh=\"onRfRefresh\"\n\t@update:refreshing=\"onRfRefreshing\"\n\t@load=\"onRfLoad\"\n>\n\t<template #header>\n\t\t<view class=\"list-header\">\n\t\t\t<text>批次 #{{ rfBatch }} · {{ rfList.length }} 条</text>\n\t\t</view>\n\t</template>\n\t<template #default=\"{ item, index }\">\n\t\t<nax-cell :title=\"readTitle(item)\" :value=\"indexLabel(index)\"></nax-cell>\n\t</template>\n</nax-virtual-list>\n```\n\n```uts\nconst rfList = ref([] as UTSJSONObject[])\nconst rfLoading = ref(false)\nconst rfFinished = ref(false)\nconst rfRefreshing = ref(false)\nconst rfBatch = ref(1)\nlet rfSeed = 0\n\nfunction onRfRefreshing(v : boolean) {\n\trfRefreshing.value = v\n}\n\n// 触底加载：400ms 后追加 25 条\nfunction onRfLoad() {\n\tif (rfLoading.value || rfFinished.value || rfRefreshing.value) {\n\t\treturn\n\t}\n\trfLoading.value = true\n\tsetTimeout(() => {\n\t\tappendRf(25)\n\t\trfLoading.value = false\n\t\tif (rfList.value.length >= 120) {\n\t\t\trfFinished.value = true\n\t\t}\n\t}, 400)\n}\n\n// 下拉刷新：500ms 后换新批次，批次号 +1\nfunction onRfRefresh() {\n\trfRefreshing.value = true\n\trfFinished.value = false\n\tsetTimeout(() => {\n\t\trfBatch.value = rfBatch.value + 1\n\t\trfSeed = 0\n\t\trfList.value = [] as UTSJSONObject[]\n\t\tappendRf(30)\n\t\trfRefreshing.value = false\n\t\trfLoading.value = false\n\t}, 500)\n}\n\nfunction appendRf(count : number) {\n\tconst next = [] as UTSJSONObject[]\n\tvar n = 0\n\twhile (n < count) {\n\t\tconst id = rfSeed\n\t\trfSeed++\n\t\tnext.push(makeItem(id, 'B' + rfBatch.value.toString()))\n\t\tn++\n\t}\n\tconst merged = [] as UTSJSONObject[]\n\tvar j = 0\n\tconst cur = rfList.value\n\twhile (j < cur.length) {\n\t\tmerged.push(cur[j])\n\t\tj++\n\t}\n\tvar k = 0\n\twhile (k < next.length) {\n\t\tmerged.push(next[k])\n\t\tk++\n\t}\n\trfList.value = merged\n}\n```"
  },
  {
    heading: '空状态',
    body: "```uvue\n<nax-virtual-list\n\theight=\"200px\"\n\t:list=\"emptyList\"\n\t:item-height=\"48\"\n\t:empty=\"true\"\n\tempty-text=\"还没有虚拟列表数据\"\n></nax-virtual-list>\n```\n\n```uts\nconst emptyList = ref([] as UTSJSONObject[])\n```"
  }
]
